AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CVPilot Backend API
  
  AI/ML 연구자를 위한 종합 분석 플랫폼 백엔드

# 글로벌 설정
Globals:
  Function:
    Timeout: 300  # 5분 (LLM 분석 시간 고려)
    MemorySize: 1024  # 1GB (AI 모델 로딩 고려)
    Runtime: python3.9
    Environment:
      Variables:
        PYTHONPATH: /var/task
        AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
        
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  Stage:
    Type: String
    Default: prod
    Description: API Gateway stage name
    
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key
    
  SupabaseUrl:
    Type: String
    Description: Supabase URL
    
  SupabaseKey:
    Type: String
    NoEcho: true
    Description: Supabase Key

Resources:
  CVPilotApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'cvpilot-backend-${Stage}'
      CodeUri: .
      Handler: lambda_handler.lambda_handler
      Description: CVPilot Backend API Lambda Function
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_KEY: !Ref SupabaseKey
          STAGE: !Ref Stage
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref CVPilotApiGateway
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: GET
            RestApiId: !Ref CVPilotApiGateway
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref CVPilotApiGateway

  CVPilotApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'cvpilot-api-${Stage}'
      StageName: !Ref Stage
      Description: CVPilot API Gateway
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  CVPilotApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${CVPilotApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
      
  CVPilotApiId:
    Description: "API Gateway ID"
    Value: !Ref CVPilotApiGateway
    Export:
      Name: !Sub "${AWS::StackName}-ApiId" 